global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
- job_name: scylla
  metrics_path: /metrics
  static_configs:
  - targets: [ "scylla:9180" ]

- job_name: scylla_node
  metrics_path: /metrics
  static_configs:
  - targets: [ "scylla:9100" ]

- job_name: indexer
  metrics_path: /metrics
  static_configs:
  - targets: [ "indexer:9101" ]

- job_name: api
  metrics_path: /metrics
  static_configs:
  - targets: [ "api:4000" ]

- job_name: nats
  metrics_path: /metrics
  static_configs:
  - targets: [ "nats-surveyor:7777" ]
